version: '3.8'

services:
  web:
    build:
      context: https://github.com/santi666qnk/GestionCasa.git
      dockerfile: Dockerfile
    ports:
        - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://oregon-postgres.render.com:5432/gestioncasa
      - SPRING_DATASOURCE_USERNAME=santi
      - SPRING_DATASOURCE_PASSWORD=bWvagIZV5pcOqRMUzoyZREJfo4hvH4PT
      - SPRING_PROFILES_ACTIVE=production
    command: ["java", "-jar", "/app.jar"]
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=gestioncasa
      - POSTGRES_USER=santi
      - POSTGRES_PASSWORD=bWvagIZV5pcOqRMUzoyZREJfo4hvH4PT
    ports:
      - "5432:5432"