version: '3.3'

services:
  web:
    build:
      context: https://github.com/santi666qnk/GestionCasa.git
      dockerfile: Dockerfile
    ports:
        - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://192.168.1.127:5433/gestioncasa
      - SPRING_DATASOURCE_USERNAME=Santi
      - SPRING_DATASOURCE_PASSWORD=gancho666
      - SPRING_PROFILES_ACTIVE=production
    command: ["java", "-jar", "/app.jar"]
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=gestioncasa
      - POSTGRES_USER=Santi
      - POSTGRES_PASSWORD=gancho666
    ports:
      - "5432:5432"